University.Web/Controllers/InstructorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using University.BL.Models;
using University.BL.Repositories;
using University.BL.Repositories.Implements;
using AutoMapper;
using University.BL.DTOs;
using University.BL.Controls;
using Newtonsoft.Json;

namespace University.Web.Controllers
{
    public class InstructorsController : Controller
    {
        private readonly IMapper mapper = MvcApplication.MapperConfiguration.CreateMapper();
        private readonly IInstructorRepository instructorRepository = new InstructorRepository(new UniversityModel());
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> IndexJson()
        {
            var instructorsModel = await instructorRepository.GetAll();
            var instructorsDTO = instructorsModel.Select(x => mapper.Map<InstructorDTO>(x));
            return Json(instructorsDTO, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<ActionResult> GetInstructors()
        {
            var instructorsModel = await instructorRepository.GetAll();
            var instructorsDTO = instructorsModel.Select(x => mapper.Map<InstructorDTO>(x));
            var instructorsSelect = instructorsDTO.Select(x => new SelectControl
            {
                Id = x.ID,
                Text = x.FullName
            });

            return Json(JsonConvert.SerializeObject(instructorsSelect), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return PartialView(new InstructorDTO());
        }

        [HttpPost]
        public async Task<ActionResult> Create(InstructorDTO instructorDTO)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var instructorModel = mapper.Map<Instructor>(instructorDTO);
                    await instructorRepository.Insert(instructorModel);
                }
                return Json(new ResponseDTO
                {
                    Message = "The process is successful",
                    IsSuccess = true
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new ResponseDTO
                {
                    Message = ex.Message,
                    IsSuccess = false
                }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            var instructorModel = await instructorRepository.GetById(id);
            var instructortDTO = mapper.Map<InstructorDTO>(instructorModel);
            return PartialView(instructortDTO);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(InstructorDTO instructorDTO)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var instructorModel = mapper.Map<Instructor>(instructorDTO);
                    await instructorRepository.Update(instructorModel);
                }
                return Json(new ResponseDTO
                {
                    Message = "The process is successful",
                    IsSuccess = true
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new ResponseDTO
                {
                    Message = ex.Message,
                    IsSuccess = false
                }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                await instructorRepository.Delete(id);

                return Json(new ResponseDTO
                {
                    Message = "The process is successful",
                    IsSuccess = true
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new ResponseDTO
                {
                    Message = ex.Message,
                    IsSuccess = false
                }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

University.Web/Views/Instructors/Create.cshtml
@model University.BL.DTOs.InstructorDTO


@using (Html.BeginForm("Create", "Instructors", FormMethod.Post, new { id = "formCreateInstructor" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>InstructorDTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstMidName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstMidName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstMidName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HireDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HireDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HireDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="create-save" type="button" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script>

    $("#create-save").click(function () {
        createInstructor();
    })

    function createInstructor() {
        

        var formData = $("#formCreateInstructor").serialize();

        $.post(urlBase + "/Instructors/Create", formData).done(function (data) {
            console.table(data);


            if (data.IsSuccess) {
                swal("Notification", "The process is successful", "success");
                $("#modalInstructors").modal("hide");
                getInstructors();
            } else {
                swal("Notification", "The process is failed", "error");
            }


        }).fail(function (data) {
            console.table(data);
            swal("Notification", "The process is failed", "error");
        })
    }
</script>

University.Web/Views/Instructors/Edit.cshtml
@model University.BL.DTOs.InstructorDTO


@using (Html.BeginForm("Edit", "Instructors", FormMethod.Post, new { id = "formEditInstructor" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>InstructorDTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstMidName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstMidName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstMidName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HireDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HireDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HireDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="edit-save" type="button" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<script>

    $("#edit-save").click(function () {
        editInstructor();
    })

    function editInstructor() {

        var formData = $("#formEditInstructor").serialize();

        $.post(urlBase + "/Instructors/Edit", formData).done(function (data) {
            console.table(data);


            if (data.IsSuccess) {
                swal("Notification", "The process is successful", "success");
                $("#modalInstructors").modal("hide");
                getInstructors();
            } else {
                swal("Notification", "The process is failed", "error");
            }


        }).fail(function (data) {
            console.table(data);
            swal("Notification", "The process is failed", "error");
        })
    }
</script>

University.Web/Views/Instructors/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Instructors</h2>

<!-- Button trigger modal -->
<button id="create" type="button" class="btn btn-success fas fa-plus">
    Agregar
</button>
<hr />

<div id="rowInstructors">
    <div id="divInstructors">
        <table id="tableInstructors" class="table table-bordered" style="width:100%">
        </table>
    </div>

</div>


<!-- Modal -->
<div class="modal fade" id="modalInstructors" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Instructors</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>




<script>
    $(document).ready(function () {
        getInstructors();
    });

    $("#create").click(function () {
        $("#modalInstructors .modal-body", this).empty();
        $("#modalInstructors .modal-body").load(urlBase + "/Instructors/Create");
        $("#modalInstructors").modal("show");
    });

    function getInstructors() {
        var $row = $('#rowInstructors');
        $('#divInstructors').remove();
        var $div = $('<div></div>');
        $div.addClass('table-responsive mb-5');
        $div.attr({ id: 'divInstructors' });
        $div.addClass('divInstructors mb-5');
        var $table = $("<table></table>");
        $table.addClass('table table-bordered display text-center');
        $table.attr({ id: 'tableInstructors', width: '100%' });
        $div.append($table);
        $row.append($div);

        $.get(urlBase + '/Instructors/IndexJson').done(function (data) {
            $.notify("Load data", "info");
            console.table(data)

            table = $('#tableInstructors').DataTable({
                data: data,
                "iDisplayLength": 10,
                "order": [[0, "desc"]],
                columns: [
                    { title: 'ID', data: 'ID', className: 'd-none' },
                    { title: 'LastName', data: 'LastName' },
                    { title: 'FirstMidName', data: 'FirstMidName' },
                    { title: 'HireDate', data: 'HireDateFormat' },
                    { title: 'Options', data: null }
                ],
                columnDefs: [
                    {
                        targets: 4,
                        render: function (data, type, row) {
                            return '<a href="javascript:void" class="btn btn-warning edit fas fa-edit"> Edit</a>' +
                                '<a href="javascript:void" class="btn btn-danger delete fas fa-trash"> Delete</a>';
                        }
                    }
                ]
            });

            $('#tableInstructors').on('click', 'tbody a.edit', function (e) {
                let id = $(this).parent().siblings('td')[0].innerText;

                $('#modalInstructors .modal-body', this).empty();
                $('#modalInstructors .modal-body').load(urlBase + '/Instructors/Edit/' + id);
                $("#modalInstructors").modal("show");
            });

            $('#tableInstructors').on('click', 'tbody a.delete', function (data) {
                let id = $(this).parent().siblings('td')[0].innerText;
                deleteInstructor(id);
            });

        }).fail(function (data) {
            console.table(data);
        });
    }

    

    function deleteInstructor(id) {
        swal({
            title: "Are you sure?",
            text: "You will not be able to recover this register!",
            type: "warning",
            showCancelButton: true,
            confirmButtonClass: "btn-danger",
            confirmButtonText: "Yes, delete it!",
            cancelButtonText: "No, cancel plx!",
            closeOnConfirm: false,
            closeOnCancel: false
        },
            function (isConfirm) {
                if (isConfirm) {

                    $.get(urlBase + "/Instructors/Delete/" + id, function (data) {
                        if (data.IsSuccess) {
                            getInstructors();
                            swal("Deleted!", "Your register has been deleted.", "success");
                        } else {
                            swal("Notification", data.Message, "error");
                        }
                    }).fail(function (data) {
                        swal("Notification", data.Message, "error");
                    })
                } else {
                    swal("Cancelled", "Your register is safe :)", "error");
                }
            });
    }
</script>