University.Web/Controllers/OfficesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using University.BL.Models;
using University.BL.Repositories;
using University.BL.Repositories.Implements;
using AutoMapper;
using University.BL.DTOs;
using University.BL.Controls;
using Newtonsoft.Json;

namespace University.Web.Controllers
{
    public class OfficesController : Controller
    {
        private readonly IMapper mapper = MvcApplication.MapperConfiguration.CreateMapper();
        private readonly IOfficeAssignmentRepository officeRepository = new OfficeAssignmentRepository(new UniversityModel());
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> IndexJson()
        {
            var officesModel = await officeRepository.GetAll();
            var officesDTO = officesModel.Select(x => mapper.Map<OfficeAssignmentDTO>(x));
            return Json(officesDTO, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<ActionResult> GetOffices()
        {
            var officesModel = await officeRepository.GetAll();
            var officesDTO = officesModel.Select(x => mapper.Map<OfficeAssignmentDTO>(x));
            var officesSelect = officesDTO.Select(x => new SelectControl
            {
                Id = x.InstructorID,
                Text = x.Location
            });

            return Json(JsonConvert.SerializeObject(officesSelect), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return PartialView(new OfficeAssignmentDTO());
        }

        [HttpPost]
        public async Task<ActionResult> Create(OfficeAssignmentDTO officeDTO)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var officeModel = mapper.Map<OfficeAssignment>(officeDTO);
                    await officeRepository.Insert(officeModel);
                }
                return Json(new ResponseDTO
                {
                    Message = "The process is successful",
                    IsSuccess = true
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new ResponseDTO
                {
                    Message = ex.Message,
                    IsSuccess = false
                }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            var officeModel = await officeRepository.GetById(id);
            var officeDTO = mapper.Map<OfficeAssignmentDTO>(officeModel);
            return PartialView(officeDTO);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(OfficeAssignmentDTO officeDTO)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var officeModel = mapper.Map<OfficeAssignment>(officeDTO);
                    await officeRepository.Update(officeModel);
                }
                return Json(new ResponseDTO
                {
                    Message = "The process is successful",
                    IsSuccess = true
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new ResponseDTO
                {
                    Message = ex.Message,
                    IsSuccess = false
                }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                await officeRepository.Delete(id);

                return Json(new ResponseDTO
                {
                    Message = "The process is successful",
                    IsSuccess = true
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new ResponseDTO
                {
                    Message = ex.Message,
                    IsSuccess = false
                }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

University.Web/Views/Offices/Create.cshtml
@model University.BL.DTOs.OfficeAssignmentDTO



@using (Html.BeginForm("Create", "Offices", FormMethod.Post, new { id = "formCreateOffice" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OfficeAssignmentDTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.InstructorID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select id="InstructorID" name="InstructorID" class="form-control"></select>

                @Html.ValidationMessageFor(model => model.InstructorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="create-save" type="button" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<script>
    $(document).ready(function () {
        getInstructorsList();
    });
    $("#create-save").click(function () {
        createOffice();
    })

    function createOffice() {
        //var courseID = document.getElementById("CourseID");
        //var courseID = $("#CourseID").val();

        var formData = $("#formCreateOffice").serialize();

        $.post(urlBase + "/Offices/Create", formData).done(function (data) {
            console.table(data);


            if (data.IsSuccess) {
                swal("Notification", "The process is successful", "success");
                $("#modalOffices").modal("hide");
                getOffices();
            } else {
                swal("Notification", "The process is failed", "error");
            }


        }).fail(function (data) {
            console.table(data);
            swal("Notification", "The process is failed", "error");
        })
    }

    function getInstructorsList() {
        $.get(urlBase + '/Instructors/GetInstructors', function (data) {
            $("#InstructorID").empty();
            $("#InstructorID").select2({
                placeholder: "Seleccione",
                data: JSON.parse(data)
            });
            $("#InstructorID").val("").trigger("change");
        });
    }
</script>

University.Web/Views/Offices/Edit.cshtml
@model University.BL.DTOs.OfficeAssignmentDTO



@using (Html.BeginForm("Edit", "Offices", FormMethod.Post, new { id = "formEditOffice" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.InstructorID)
    <div class="form-horizontal">
        <h4>OfficeAssignmentDTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="edit-save" type="button" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<script>

    $("#edit-save").click(function () {
        editOffice();
    })

    function editOffice() {

        var formData = $("#formEditOffice").serialize();

        $.post(urlBase + "/Offices/Edit", formData).done(function (data) {
            console.table(data);


            if (data.IsSuccess) {
                swal("Notification", "The process is successful", "success");
                $("#modalOffices").modal("hide");
                getOffices();
            } else {
                swal("Notification", "The process is failed", "error");
            }


        }).fail(function (data) {
            console.table(data);
            swal("Notification", "The process is failed", "error");
        })
    }
</script>

University.Web/Views/Offices/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Offices</h2>

<select id="OfficeSelect" class="form-control"></select>
<hr />

<!-- Button trigger modal -->
<button id="create" type="button" class="btn btn-success fas fa-plus">
    Agregar
</button>
<hr />

<div id="rowOffices">
    <div id="divOffices">
        <table id="tableOffices" class="table table-bordered" style="width:100%">
        </table>
    </div>

</div>


<!-- Modal -->
<div class="modal fade" id="modalOffices" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Offices</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>




<script>
    $(document).ready(function () {
        getOffices();
        getOfficesList();
    });

    $("#create").click(function () {
        $("#modalOffices .modal-body", this).empty();
        $("#modalOffices .modal-body").load(urlBase + "/Offices/Create");
        $("#modalOffices").modal("show");
    });

    function getOffices() {
        var $row = $('#rowOffices');
        $('#divOffices').remove();
        var $div = $('<div></div>');
        $div.addClass('table-responsive mb-5');
        $div.attr({ id: 'divOffices' });
        $div.addClass('divOffices mb-5');
        var $table = $("<table></table>");
        $table.addClass('table table-bordered display text-center');
        $table.attr({ id: 'tableOffices', width: '100%' });
        $div.append($table);
        $row.append($div);

        $.get(urlBase + '/Offices/IndexJson').done(function (data) {
            $.notify("Load data", "info");
            console.table(data)

            table = $('#tableOffices').DataTable({
                data: data,
                "iDisplayLength": 10,
                "order": [[0, "desc"]],
                columns: [
                    { title: 'ID', data: 'InstructorID', className: 'd-none' },
                    { title: 'Location', data: 'Location' },
                    { title: 'Instructor', data: 'InstructorFormat' },
                    { title: 'Options', data: null }
                ],
                columnDefs: [
                    {
                        targets: 3,
                        render: function (data, type, row) {
                            return '<a href="javascript:void" class="btn btn-warning edit fas fa-edit"> Edit</a>' +
                                '<a href="javascript:void" class="btn btn-danger delete fas fa-trash"> Delete</a>';
                        }
                    }
                ]
            });

            $('#tableOffices').on('click', 'tbody a.edit', function (e) {
                let id = $(this).parent().siblings('td')[0].innerText;

                $('#modalOffices .modal-body', this).empty();
                $('#modalOffices .modal-body').load(urlBase + '/Offices/Edit/' + id);
                $("#modalOffices").modal("show");
            });

            $('#tableOffices').on('click', 'tbody a.delete', function (data) {
                let id = $(this).parent().siblings('td')[0].innerText;
                deleteOffice(id);
            });

        }).fail(function (data) {
            console.table(data);
        });
    }

    

    function deleteOffice(id) {
        swal({
            title: "Are you sure?",
            text: "You will not be able to recover this register!",
            type: "warning",
            showCancelButton: true,
            confirmButtonClass: "btn-danger",
            confirmButtonText: "Yes, delete it!",
            cancelButtonText: "No, cancel plx!",
            closeOnConfirm: false,
            closeOnCancel: false
        },
            function (isConfirm) {
                if (isConfirm) {

                    $.get(urlBase + "/Offices/Delete/" + id, function (data) {
                        if (data.IsSuccess) {
                            getOffices();
                            swal("Deleted!", "Your register has been deleted.", "success");
                        } else {
                            swal("Notification", data.Message, "error");
                        }
                    }).fail(function (data) {
                        swal("Notification", data.Message, "error");
                    })
                } else {
                    swal("Cancelled", "Your register is safe :)", "error");
                }
            });
    }

    function getOfficesList() {
        $.get(urlBase + '/Offices/GetOffices', function (data) {
            $("#OfficeSelect").empty();
            $("#OfficeSelect").select2({
                placeholder: "Seleccione",
                data: JSON.parse(data)
            });
            $("#OfficeSelect").val("").trigger("change");
        });
    }
</script>